Warning: downloaded length 0 != reported length 250

Warning: cannot open URL
'https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.20/data/annotation/bin/windows/contrib/4.4/PACKAGES.rds':
HTTP status was '404 Not Found'

Warning: downloaded length 0 != reported length 250

Warning: cannot open URL
'https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.20/data/annotation/bin/windows/contrib/4.4/PACKAGES.gz':
HTTP status was '404 Not Found'

Warning: downloaded length 0 != reported length 250

Warning: cannot open URL
'https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.20/data/experiment/bin/windows/contrib/4.4/PACKAGES.rds':
HTTP status was '404 Not Found'

Warning: downloaded length 0 != reported length 250

Warning: cannot open URL
'https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.20/data/experiment/bin/windows/contrib/4.4/PACKAGES.gz':
HTTP status was '404 Not Found'

Warning: downloaded length 0 != reported length 250

Warning: cannot open URL
'https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.20/workflows/bin/windows/contrib/4.4/PACKAGES.rds':
HTTP status was '404 Not Found'

Warning: downloaded length 0 != reported length 250

Warning: cannot open URL
'https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.20/workflows/bin/windows/contrib/4.4/PACKAGES.gz':
HTTP status was '404 Not Found'

Warning: downloaded length 0 != reported length 11781

Warning: cannot open URL
'https://bioconductor.org/packages/3.20/books/bin/windows/contrib/4.4/PACKAGES.rds':
HTTP status was '404 Not Found'

Warning: downloaded length 0 != reported length 11781

Warning: cannot open URL
'https://bioconductor.org/packages/3.20/books/bin/windows/contrib/4.4/PACKAGES.gz':
HTTP status was '404 Not Found'

Error in library(biostrings) : there is no package called ‘biostrings’
Traceback:
2: stop(packageNotFoundError(package, lib.loc, sys.call()))
1: library(biostrings)

